{
  "openapi": "3.0.0",
  "info": {
    "description": "Cabot Models API",
    "title": "Cabot Models API",
    "version": "0.1.0",
    "contact": {
      "name": "FactSet Research Systems",
      "email": "api@factset.com",
      "url": "https://developer.factset.com/contact"
    },
    "license": {
      "name": "Apache License, Version 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0"
    }
  },
  "servers": [
    {
      "url": "https://api.factset.com/analytics/cabot/v0",
      "description": "Production server"
    }
  ],
  "externalDocs": {
    "description": "API Documentation",
    "url": "https://developer.factset.com/api-catalog/cabot"
  },
  "paths": {
    "/models/skills": {
      "get": {
        "tags": [
          "Cabot Models API"
        ],
        "description": "Cabot main path for Skills API.",
        "operationId": "getSkillsModelAnalytic",
        "parameters": [
          {
            "name": "accountPath",
            "in": "query",
            "required": true,
            "description": "The account path of the portfolio you want to retrieve the data for.",
            "schema": {
              "$ref": "#/components/schemas/AccountPath"
            }
          },
          {
            "name": "benchmarkPath",
            "in": "query",
            "required": true,
            "description": "The path of the benchmark you want to retrieve the data for.<br /><br />",
            "schema": {
              "$ref": "#/components/schemas/BenchmarkPath"
            }
          },
          {
            "name": "period",
            "in": "query",
            "description": "For which period you want to retrieve the data.<br />There are four options available as follows:<br /><br />1 -> YYYY (Repeating One Year)<br /><br />2 -> YYYY-YYYY (Repeating Three/Five/Ten Year)<br /><br />3 -> 1M_TRAILING, 3M_TRAILING, 1Y_TRAILING, 3Y_TRAILING, 5Y_TRAILING, (Trailing Periods (If available for your portfolio))<br /><br />4 -> INCEPTION_TO_DATE<br /><br />You can only get the data for one period per request.<br /><br />",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/Period"
            }
          },
          {
            "name": "attribute",
            "in": "query",
            "description": "The attribute represents the different factors.<br />You can choose which of them (if any) you want to see analytics for.<br /><br />If provided, the API response will contain both \"LOW\" and \"HIGH\" values for it.<br /><br />",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/Attributes"
            }
          },
          {
            "name": "sector",
            "in": "query",
            "description": "Sector represents the sector based on the company's industry breakdown.<br />You can choose which of them (if any) you want to see analytics for.<br /><br />",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/Sectors"
            },
            "example": "energy"
          },
          {
            "name": "region",
            "in": "query",
            "description": "Region of domicile represents the region based on the company's primary listing.<br />You can choose which of them (if any) you want to see analytics for.<br /><br />",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/Regions"
            },
            "example": "northAmerica"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "X-FactSet-Api-RateLimit-Limit": {
                "description": "Number of allowed requests for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Remaining": {
                "description": "Number of requests left for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Reset": {
                "description": "Number of seconds remaining till rate limit resets.",
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SkillsResponseRoot"
                },
                "examples": {
                  "No attribute was provided in the request": {
                    "value": {
                      "data": {
                        "skillValues": {
                          "buy": 1.48,
                          "sell": -0.58,
                          "sizing": 0.15
                        },
                        "attribute": null
                      }
                    }
                  },
                  "An attribute was provided in the request": {
                    "value": {
                      "data": {
                        "lowSkillValues": {
                          "buy": 0.03,
                          "sell": 0.24,
                          "sizing": 0.37
                        },
                        "highSkillValues": {
                          "buy": 2.06,
                          "sell": -0.88,
                          "sizing": 0.75
                        },
                        "attribute": "QFL_DEBT_ASSETS"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request, invalid query parameters.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "X-FactSet-Api-RateLimit-Limit": {
                "description": "Number of allowed requests for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Remaining": {
                "description": "Number of requests left for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Reset": {
                "description": "Number of seconds remaining till rate limit resets.",
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ClientErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid authentication.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              }
            }
          },
          "403": {
            "description": "User is forbidden with current credentials.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "X-FactSet-Api-RateLimit-Limit": {
                "description": "Number of allowed requests for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Remaining": {
                "description": "Number of requests left for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Reset": {
                "description": "Number of seconds remaining till rate limit resets.",
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "Path not found",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "X-FactSet-Api-RateLimit-Limit": {
                "description": "Number of allowed requests for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Remaining": {
                "description": "Number of requests left for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Reset": {
                "description": "Number of seconds remaining till rate limit resets.",
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ClientErrorResponse"
                }
              }
            }
          },
          "415": {
            "description": "Missing/Invalid Content-Type header. Header needs to be set to application/json.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "X-FactSet-Api-RateLimit-Limit": {
                "description": "Number of allowed requests for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Remaining": {
                "description": "Number of requests left for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Reset": {
                "description": "Number of seconds remaining till rate limit resets.",
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "429": {
            "description": "Rate limit reached. Wait till the time specified in Retry-After header value to make further requests.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "Retry-After": {
                "description": "Time to wait in seconds before making a new request as the rate limit has reached.",
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Server error.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              }
            }
          },
          "503": {
            "description": "Request timed out. Retry the request in some time",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              }
            }
          }
        },
        "summary": "Cabot main path for Skills API"
      },
      "parameters": []
    },
    "/models/sell-timing": {
      "get": {
        "tags": [
          "Cabot Models API"
        ],
        "description": "Cabot main path for Sell Timing API",
        "operationId": "getSellTimingModelAnalytic",
        "parameters": [
          {
            "name": "accountPath",
            "in": "query",
            "required": true,
            "description": "The account path of the portfolio you want to retrieve the data for.<br /><br />",
            "schema": {
              "$ref": "#/components/schemas/AccountPath"
            }
          },
          {
            "name": "benchmarkPath",
            "in": "query",
            "required": true,
            "description": "The path of the benchmark you want to retrieve the data for.<br /><br />",
            "schema": {
              "$ref": "#/components/schemas/BenchmarkPath"
            }
          },
          {
            "name": "period",
            "in": "query",
            "description": "For which period you want to retrieve the data.<br />There are four options available as follows:<br /><br />1 -> YYYY (Repeating One Year)<br /><br />2 -> YYYY-YYYY (Repeating Three/Five/Ten Year)<br /><br />3 -> 1M_TRAILING, 3M_TRAILING, 1Y_TRAILING, 3Y_TRAILING, 5Y_TRAILING, (Trailing Periods (If available for your portfolio))<br /><br />4 -> INCEPTION_TO_DATE<br /><br />You can only get the data for one period per request.<br /><br />",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/Period"
            },
            "example": "2015-2017"
          },
          {
            "name": "attribute",
            "in": "query",
            "description": "The attribute represents the different factors.<br />You can choose which of them (if any) you want to see analytics for.<br /><br />If provided, the API response will contain both \"LOW\" and \"HIGH\" values for it.<br /><br />",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/Attributes"
            },
            "example": "QFL_EY"
          },
          {
            "name": "sector",
            "in": "query",
            "description": "Sector represents the sector based on the company's industry breakdown.<br />You can choose which of them (if any) you want to see analytics for.<br /><br />",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/Sectors"
            },
            "example": "energy"
          },
          {
            "name": "region",
            "in": "query",
            "description": "Region of domicile represents the region based on the company's primary listing.<br />You can choose which of them (if any) you want to see analytics for.<br /><br />",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/Regions"
            },
            "example": "northAmerica"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "X-FactSet-Api-RateLimit-Limit": {
                "description": "Number of allowed requests for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Remaining": {
                "description": "Number of requests left for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Reset": {
                "description": "Number of seconds remaining till rate limit resets.",
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/SellTimingResponseRoot"
                },
                "examples": {
                  "No attribute was provided in the request": {
                    "value": {
                      "data": {
                        "sellTimingValues": {
                          "youngerWinner": 1.48,
                          "youngerLoser": -0.58,
                          "olderWinner": 0.15,
                          "olderLoser": 2
                        },
                        "attribute": null
                      }
                    }
                  },
                  "Attribute was provided in the request": {
                    "value": {
                      "data": {
                        "highSellTimingValues": {
                          "youngerWinner": 1.48,
                          "youngerLoser": -0.58,
                          "olderWinner": 0.15,
                          "olderLoser": 2
                        },
                        "lowSellTimingValues": {
                          "youngerWinner": 1.48,
                          "youngerLoser": -0.58,
                          "olderWinner": 0.15,
                          "olderLoser": 2
                        },
                        "attribute": "QFL_SALES_GR_1Y"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad request, invalid query parameters.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "X-FactSet-Api-RateLimit-Limit": {
                "description": "Number of allowed requests for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Remaining": {
                "description": "Number of requests left for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Reset": {
                "description": "Number of seconds remaining till rate limit resets.",
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ClientErrorResponse"
                }
              }
            }
          },
          "401": {
            "description": "Missing or invalid authentication.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              }
            }
          },
          "403": {
            "description": "User is forbidden with current credentials.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "X-FactSet-Api-RateLimit-Limit": {
                "description": "Number of allowed requests for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Remaining": {
                "description": "Number of requests left for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Reset": {
                "description": "Number of seconds remaining till rate limit resets.",
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "404": {
            "description": "Path not found",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "X-FactSet-Api-RateLimit-Limit": {
                "description": "Number of allowed requests for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Remaining": {
                "description": "Number of requests left for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Reset": {
                "description": "Number of seconds remaining till rate limit resets.",
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ClientErrorResponse"
                }
              }
            }
          },
          "415": {
            "description": "Missing/Invalid Content-Type header. Header needs to be set to application/json.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "X-FactSet-Api-RateLimit-Limit": {
                "description": "Number of allowed requests for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Remaining": {
                "description": "Number of requests left for the time window.",
                "schema": {
                  "type": "string"
                }
              },
              "X-FactSet-Api-RateLimit-Reset": {
                "description": "Number of seconds remaining till rate limit resets.",
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "429": {
            "description": "Rate limit reached. Wait till the time specified in Retry-After header value to make further requests.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              },
              "Retry-After": {
                "description": "Time to wait in seconds before making a new request as the rate limit has reached.",
                "schema": {
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Server error.",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              }
            }
          },
          "503": {
            "description": "Request timed out. Retry the request in some time",
            "headers": {
              "X-DataDirect-Request-Key": {
                "description": "FactSet's request key header.",
                "schema": {
                  "type": "string",
                  "description": "FactSet's request key header."
                }
              },
              "X-FactSet-Api-Request-Key": {
                "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication.",
                "schema": {
                  "type": "string",
                  "description": "Key to uniquely identify an Analytics API request. Only available after successful authentication."
                }
              }
            }
          }
        },
        "summary": "Cabot main path for Sell Timing API"
      },
      "parameters": []
    }
  },
  "security": [
    {
      "FactSetApiKey": []
    },
    {
      "FactSetOAuth2": []
    }
  ],
  "components": {
    "securitySchemes": {
      "FactSetOAuth2": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://auth.factset.com/as/token.oauth2",
            "scopes": {}
          }
        }
      },
      "FactSetApiKey": {
        "type": "http",
        "scheme": "basic"
      }
    },
    "schemas": {
      "SkillsResponseRoot": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/SkillsResponseOptions"
          }
        }
      },
      "SkillsResponseOptions": {
        "type": "object",
        "properties": {
          "highSkillValues": {
            "$ref": "#/components/schemas/SkillsModelAnalytics"
          },
          "lowSkillValues": {
            "$ref": "#/components/schemas/SkillsModelAnalytics"
          },
          "skillValues": {
            "$ref": "#/components/schemas/SkillsModelAnalytics"
          },
          "attribute": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "SellTimingResponseRoot": {
        "type": "object",
        "properties": {
          "data": {
            "$ref": "#/components/schemas/SellTimingResponseOptions"
          }
        }
      },
      "SellTimingResponseOptions": {
        "type": "object",
        "properties": {
          "highSellTimingValues": {
            "$ref": "#/components/schemas/SellTimingModelAnalytics"
          },
          "lowSellTimingValues": {
            "$ref": "#/components/schemas/SellTimingModelAnalytics"
          },
          "sellTimingValues": {
            "$ref": "#/components/schemas/SellTimingModelAnalytics"
          },
          "attribute": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "SkillsModelAnalytics": {
        "type": "object",
        "properties": {
          "buy": {
            "type": "number",
            "description": "This measures effectiveness in name selection."
          },
          "sell": {
            "type": "number",
            "description": "This quantifies the effectiveness of the sell discipline (final sells). It considers the impact from selling younger positions (i.e., too quickly, too slowly, done well) and from selling older positions (i.e., too quickly, too slowly, done well)."
          },
          "sizing": {
            "type": "number",
            "description": "This quantifies the benefit of active sizing decisions including initial position build up and subsequent trims and adds."
          }
        }
      },
      "SellTimingModelAnalytics": {
        "type": "object",
        "properties": {
          "youngerWinner": {
            "type": "number",
            "description": "Benefit of harvesting younger, winning positions."
          },
          "youngerLoser": {
            "type": "number",
            "description": "Benefit of harvesting younger, losing positions."
          },
          "olderWinner": {
            "type": "number",
            "description": "Benefit of harvesting older, winning positions"
          },
          "olderLoser": {
            "type": "number",
            "description": "Benefit of harvesting older, losing positions."
          }
        }
      },
      "AccountPath": {
        "type": "string",
        "description": "The account path of the portfolio you want to retrieve the data for.",
        "example": "Client:/Folder1/Cabot.ACCT"
      },
      "BenchmarkPath": {
        "type": "string",
        "description": "The path of the benchmark you want to retrieve the data for.",
        "example": "BENCH:SP50"
      },
      "Period": {
        "type": "string",
        "description": "For which period you want to retrieve the data."
      },
      "Regions": {
        "type": "string",
        "description": "All currently available regions.",
        "enum": [
          "africa",
          "centralAsia",
          "easternEurope",
          "middleEast",
          "northAmerica",
          "pacificRim",
          "southAmerica",
          "westernEurope"
        ]
      },
      "Sectors": {
        "type": "string",
        "description": "All currently available sectors.",
        "enum": [
          "energy",
          "materials",
          "industrials",
          "consumerDiscretionary",
          "consumerStaples",
          "healthCare",
          "financials",
          "informationTechnology",
          "communicationServices",
          "utilities",
          "realEstate",
          "equityDiversified",
          "equityHealthCare",
          "equitySelfStorage",
          "equityIndustrial",
          "equityOffice",
          "equityResidential",
          "equityRetail",
          "equityLodgingAndResorts",
          "equitySpecialty",
          "equityTimberReits",
          "equityInfrastructureReits",
          "equityDataCenters",
          "mortageHomeFinancing",
          "mortageCommercialFinancing"
        ]
      },
      "Attributes": {
        "type": "string",
        "example": "QFL_EY",
        "description": "All currently available attributes.<br/><br/>QFL_EY : EPS for the most recent 12-month period/Share price<br/>QFL_PEG : Price to Earnings/Growth rate<br/>QFL_OCFY : Operating cash flow (FF_OPER_CF)/Market value<br/>QFL_BP : Price/book value per share ratio<br/>QFL_SP : Sales to Price (SP) Net sales/Market value<br/>QFL_OCF_EARNINGS_VAR : Differences of earnings per share in both positive and negative directions<br/>QFL_DY : Indicated annual dividend/Latest close price<br/>QFL_NET_MGN : Net profit/Net sales * 100<br/>QFL_OPER_MGN : Operating Income/Net Sales * 100<br/>QFL_ROE : Net income/Total shareholders' equity<br/>QFL_CFROE : Net cash provided by/used in operating activities /Total shareholders' equity<br/>QFL_EPS_GR_5Y : Compounded annual growth rate (CAGR) of EPS over the previous 5 financial years<br/>QFL_OCF_GR_5Y : Compounded annual growth rate (CAGR) of CFO over the previous 5 financial years<br/>QFL_SALES_GR_5Y : Compounded annual growth rate (CAGR) of Revenue over the previous 5 financial years<br/>QFL_DPS_GR_5Y : Compounded annual growth rate (CAGR) of Dividend over the previous 5 financial years<br/>QFL_EPS_GR_1Y : 1Y EPS Growth,Growth rate of EPS over the previous financial years<br/>QFL_OCF_GR_1Y : Growth rate of CFO over the previous financial years<br/>QFL_SALES_GR_1Y : Growth rate of Revenue over the previous financial years<br/>QFL_LT_DEBT_EQUITY : Long-term debt/Shareholders' Equity<br/>QFL_DEBT_ASSETS : Long-term debt/total assets<br/>QFL_EBITDAEV : Represents unreported fiscal year (F1) Enterprise Value to EBITDA<br/>QFL_REVEV : Represents Enterprise Value to Revenue<br/>QFL_ROIC : Net Income/Two fiscal period average of Total Invested Capital * 100<br/>QFL_CFROIC : Net cash provided by/used in operating activities divided by the sum of the company's total shareholders' equity and its long-term liabilities<br/>",
        "enum": [
          "QFL_EY",
          "QFL_PEG",
          "QFL_OCFY",
          "QFL_BP",
          "QFL_SP",
          "QFL_OCF_EARNINGS_VAR",
          "QFL_DY",
          "QFL_NET_MGN",
          "QFL_OPER_MGN",
          "QFL_ROE",
          "QFL_CFROE",
          "QFL_EPS_GR_5Y",
          "QFL_OCF_GR_5Y",
          "QFL_SALES_GR_5Y",
          "QFL_DPS_GR_5Y",
          "QFL_EPS_GR_1Y",
          "QFL_OCF_GR_1Y",
          "QFL_SALES_GR_1Y",
          "QFL_LT_DEBT_EQUITY",
          "QFL_DEBT_ASSETS",
          "QFL_EBITDAEV",
          "QFL_REVEV",
          "QFL_ROIC",
          "QFL_CFROIC"
        ]
      },
      "ErrorSource": {
        "type": "object",
        "properties": {
          "pointer": {
            "type": "string",
            "nullable": true
          },
          "parameter": {
            "type": "string",
            "nullable": true
          }
        }
      },
      "Error": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "nullable": true
          },
          "code": {
            "type": "string",
            "nullable": true
          },
          "title": {
            "type": "string",
            "nullable": true
          },
          "detail": {
            "type": "string",
            "nullable": true
          },
          "source": {
            "$ref": "#/components/schemas/ErrorSource"
          }
        }
      },
      "ClientErrorResponse": {
        "type": "object",
        "properties": {
          "errors": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Error"
            },
            "nullable": true
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Cabot Models API",
      "description": "to derive various portfolio analysis"
    }
  ]
}